### ISSUE TITLE
[1.19.2] Zerocore log spam

### ISSUE THREAD

**Issue by Peca21** [ZeroNoRyouki/ZeroCore2#13]
I just noticed that my latest.log is pretty big and this is the text repeating in it
`[08Feb2023 20:47:18.708] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128441_(String)" because "data" is null
	at it.zerono.mods.zerocore.lib.multiblock.AbstractMultiblockPart.syncDataFrom(AbstractMultiblockPart.java:395) ~[ZeroCore2-1.19.2-2.1.30.jar%23664!/:1.19.2-2.1.30]
	at it.zerono.mods.zerocore.lib.block.AbstractModBlockEntity.syncEntityDataFrom(AbstractModBlockEntity.java:367) ~[ZeroCore2-1.19.2-2.1.30.jar%23664!/:1.19.2-2.1.30]
	at it.zerono.mods.zerocore.lib.block.AbstractModBlockEntity.onDataPacket(AbstractModBlockEntity.java:331) ~[ZeroCore2-1.19.2-2.1.30.jar%23664!/:1.19.2-2.1.30]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_205555_(ClientPacketListener.java:1053) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_7545_(ClientPacketListener.java:1052) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_5797_(ClientboundBlockEntityDataPacket.java:49) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_5797_(ClientboundBlockEntityDataPacket.java:14) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23665!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.4.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
`
This is repeated 884 times
Also I was building a reactor today so this may be the reason for spam

Full log (ZIP): [latest.zip](https://github.com/ZeroNoRyouki/ZeroCore2/files/10689899/latest.zip)
ZeroCore2-1.19.2-2.1.30,
ExtremeReactors2-1.19.2-2.0.60,
forge 43.2.4

**Comment by ZeroNoRyouki** [comment]
Thank you.

Fixed in 1.19.2-2.1.33
